services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123 # 변경
      MYSQL_DATABASE: project-db
      TZ: Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql  # named volume 사용

  backend:
    build: ./project-backend
    image: project-backend:latest
    container_name: springboot-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: # 이 부분 추가
      - .env

  frontend:
    build: ./project-frontend
    image: project-frontend:latest
    container_name: react-container
    restart: always
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes: # 최상위 레벨에 volumes 섹션 추가
  mariadb_data:
