# docker-compose.override.yml
services:
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true       # Vite용
      - CHOKIDAR_INTERVAL=1000         # 폴링 주기(ms), 필요시 조정
      - VITE_DOCKER=true     # Docker 모드엔 반드시 true
    build:
      context: ./project-frontend
      dockerfile: Dockerfile
      target: dev                        # dev 스테이지만
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./project-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"                     # 컨테이너 3000(dev 서버) 바인드

