services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    ports:
      - "3307:3306"  # 호스트 3307 <-> 컨테이너 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - project_network

  backend:
    build: ./project-backend
    container_name: springboot-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - /project-backend/.env  # DB 정보 등을 .env에서 불러오기
    networks:
      - project_network

  frontend:
    build: ./project-frontend
    container_name: react-container
    restart: always
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - project_network

volumes:
  mariadb_data:

networks:
  project_network:
    driver: bridge
